### ISSUE TITLE
Boost dependency in libsoplex

### ISSUE THREAD

**Issue by soesau** [scipopt/soplex#12]
Hi!

If libsoplex is compiled with boost the soplex/spxdefines.h includes headers from boost/multiprecision. Thus, projects using soplex need to include boost in their projects. In this case the soplex-config.cmake should include boost (find_package(boost, etc...).

This problem showed up while compiling scip 8.0.2 on Windows 10 using MSVC2022 and CMake 3.23.1.

Thank you,
 Sven

**Comment by leoneifler** [comment]
Hi Sven, sorry this took a while to answer.
[Uploading config.patch…]()

Can you check if this patch resolves the issue for you? If so then we will merge the fix. 
[config.zip](https://github.com/scipopt/soplex/files/10111146/config.zip)

**Comment by soesau** [comment]
Hi Leon,
does not work. It does, however, when I remove the `if(DEFINED SOPLEX_WITH_BOOST)`.
I managed to solve it by changing also the cmakelists.txt. I created a pull request.
