### ISSUE TITLE
git_hash.cpp missing

### ISSUE THREAD

**Issue by Transtars** [scipopt/soplex#21]
hi, I downloaded soplex-release-401.tar.gz and tried installing soplex. 
When I execute;
Cmake S- B build DCMAKE_ INSTALL_ PREFIX=$SCIPOPTDIR
An error occurred：
/Home/cc/download/oplex-release-401/src/soplex/spxgitash. cpp: 17:10: fatal error: soplex/git_ Hash.cpp: There is no such file or directory
I went to check and it was indeed not there. How should I solve this problem?
In addition, I installed it based on the following website: https://github.com/ds4dm/learn2branch/blob/master/INSTALL.md . 
According to its instructions, I should have downloaded softx-4.0.1.tgz, but the download was not successful, so I downloaded softx-release-401. tar.gz

**Comment by leoneifler** [comment]
Before I look into this, can you verify that all the incorrect commands in your issue are just typos and not present when you tried to install SoPlex? (e.g. the cmake command etc.)

Also, can you please tell me what OS you are using?

**Comment by 2814186114** [comment]
你好解决了吗
