### ISSUE TITLE
segfault with precision boosting

### ISSUE THREAD

**Issue by msheby** [scipopt/soplex#26]
When using `--loadset=settings/exact-pure-boosting.set -X=/tmp/out` with the commit cb17eb6, I get the following (under gdb) after "Boosted iteration 1":

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000660f48 in soplex::CLUFactor<boost::multiprecision::number<boost::multiprecision::backends::mpfr_float_backend<0u, (boost::multiprecision::mpfr_allocation_type)1>, (boost::multiprecision::expression_template_option)0> >::selectPivots(boost::multiprecision::number<boost::multiprecision::backends::mpfr_float_backend<0u, (boost::multiprecision::mpfr_allocation_type)1>, (boost::multiprecision::expression_template_option)0>) ()
```

If there's a way to send over my lp file privately, I'd be happy to provide it.

**Comment by leoneifler** [comment]
Hi, yes please send me the lp file (eifler at zib.de). Could you also post your full log here and tell me what versions of boost/mpfr/gmp you are using?

**Comment by leoneifler** [comment]
thank you, and thanks for reporting this bug! I will look into the issue when you send me the lp file.

**Comment by leoneifler** [comment]
Yes that seems like a bug that definitely needs fixing, I just need the lp file now ( I wrote my email above, I don't think you can send private messages on GitHub)

**Comment by leoneifler** [comment]
fixed, patch coming to GitHub soon
