### ISSUE TITLE
Option -x without filename does not print to terminal

### ISSUE THREAD

**Issue by hartmut-h** [scipopt/soplex#29]
The usage output on error for option -x tells: "(or just -x to print to terminal)", but this does not work, the "=\<solfile\>" is needed. A simple "-x" has worked some time ago. With the attached fix, -x, -y, -X, and -Y may come again with or without \<solfile\> parameter. [x-parm-fix.diff.gz](https://github.com/scipopt/soplex/files/13968511/x-parm-fix.diff.gz)

**Comment by leoneifler** [comment]
Hi, thanks for submitting this issue. I actually fixed that bug a few days ago, it just has not made its way onto the public GitHub. I will make sure that is does today.

**Comment by hartmut-h** [comment]
Hi Leon,

On Fri, 19 Jan 2024, Leon Eifler wrote:
> Closed #29 as completed.

now "soplex -x so.lp" works fine, but "soplex -x=a so.lp" gives "invalid
option "-x=a". My fix tried so solve this, with slightly different logic.

Best Regards, Hartmut

**Comment by leoneifler** [comment]
Sorry for the long time to message back, the fix was merged a while ago, already. Closing this now, unless something is still not ok
