### ISSUE TITLE
Why libsoplex + libsoplex-pic?

### ISSUE THREAD

**Issue by jacobsvante** [scipopt/soplex#39]
I'm wondering why there's two files, libsoplex.a and libsoplex-pic.a?

Shouldn't PIC be specified as an option to cmake / the compiler? Or am I misunderstanding something?

**Comment by leoneifler** [comment]
SoPlex creates both by default, and the `-pic` one is created, since it can be linked into shared libraries.

**Comment by jacobsvante** [comment]
Okay, thanks.

I can't find any documentation describing what the differences are between the library files created. What's the difference between libsoplex.a and libsoplexshared.so more than that one is static and one is dynamic?

**Comment by leoneifler** [comment]
libsoplexshared is the library for the C-interface of SoPlex (not c++). For your goal of a completely static SCIP you will not need that one (it is used for the soplex python+julia interfaces)

**Comment by jacobsvante** [comment]
Thanks for the clarification 👍
