### ISSUE TITLE
no arguments to ‘sign’ that depend on a template parameter in solverational.hpp:4659:17

### ISSUE THREAD

**Issue by bhomaidan1990** [scipopt/soplex#4]
When I try to call the `make` I get the following error:
```sh
soplex/src/soplex/solverational.hpp:4659:17: error: there are no arguments to ‘sign’ that depend on a template parameter, so a declaration of ‘sign’ must be available [-fpermissive]
       int sig = sign(_workSol._dual[r]);
                 ^~~~
```
> I'm using `Boost 1.71.0`, OS: `Ubuntu 20.04`.

Can you please tell me how to resolve it? thanks in advance.

**Comment by svigerske** [comment]
I cannot reproduce.
I took an Ubuntu 20.04 image from Docker hub, installed packages gcc g++ libboost1.71 make libgmp-dev, and compiled SoPlex with `make ZLIB=false` and didn't get any compilation error.

You may have to give more details on what you are using, in particular naming the compiler and its version, and what you did do get to this error.

**Comment by bhomaidan1990** [comment]
It turns out to be a compatibility issue with Boost, thanks for your reply.
