### ISSUE TITLE
FAQ documentation: broken links

### ISSUE THREAD

**Issue by saona-raimundo** [scipopt/soplex#45]
I was reading [FAQ from SoPlex](https://soplex.zib.de/doc/html/FAQ.php) and found the following links broken.

> 12. SoPlex means "Sequential Simplex". Is there a parallel version available?
> 
> No. Some research was done in this direction. You can find most of the results in[ http://www.zib.de/PaperWeb/abstracts/TR-96-09](http://www.zib.de/PaperWeb/abstracts/TR-96-09) and[ http://www.zib.de/PaperWeb/abstracts/SC-95-45](http://www.zib.de/PaperWeb/abstracts/SC-95-45).

Where can I find the results on a parallel solver?

**Comment by ambros-gleixner** [comment]
Hello, thank you for noticing and opening the issue. I had to dig a bit myself, but here are the correct links:
- https://nbn-resolving.org/urn:nbn:de:0297-zib-5386 for the PhD thesis of Roland Wunderling, and
- https://nbn-resolving.org/urn:nbn:de:0297-zib-2112 for the preprint "Parallelizing the Dual Simplex Method" by Robert E. Bixby and Alexander Martin.

The FAQ will be corrected with the next release.
