### ISSUE TITLE
how should I load MPS files?

### ISSUE THREAD

**Issue by BrannonKing** [scipopt/soplex#8]
It looks like the basis loader that uses MPS files is excluded from the build. What is the recommended way to load MPS files for Soplex? Is there some 3rd-party loader that is recommended?

**Comment by leoneifler** [comment]
I'm not sure I understand your question. On the command line, you can read a .bas file using `--readbas=<basfile>`. Using the API it is `readBasisFile`.

**Comment by BrannonKing** [comment]
`readBasisFile` doesn't read the MPS format, true?

**Comment by leoneifler** [comment]
The documentation states (and I have no reason to doubt it):
```


Load basis from filename in MPS format. If rowNames and colNames are NULL, default names are used for the constraints and variables.
```

**Comment by BrannonKing** [comment]
My doubt came from the MPS reader being commented out here: https://github.com/scipopt/soplex/blob/22a415c791853db4e3614873cbd923e4f1cd3cd1/src/soplex.hpp#L9403

However, I see now that the `readBasis` method is implemented. I just hope it reads the whole problem and not just the basis.
