### ISSUE TITLE
how can I make a custom pivot rule?

### ISSUE THREAD

**Issue by BrannonKing** [scipopt/soplex#9]
Is soplex designed to support custom pivot rules? Is there some way to inject one (with selection computed from the basis and non-basis data)? I don't see it in the documentation.

**Comment by leoneifler** [comment]
You can add a custom rule by implementing either a custom ratio test or a custom pricer to influence the columns leaving/entering the basis. Could you provide some more information on what you want to achieve?

**Comment by BrannonKing** [comment]
Yes, I wanted to implement a custom pricer. And I need to be able to walk outside the feasible region. Is that something that Soplex can deal with?

**Comment by leoneifler** [comment]
I seem to have missed this follow-up question: If you are running dual Simplex you will always be primal infeasible until you find the optimum. Is this what you mean? Usually the solver will attempt to maintain either primal feasibility (in primal simplex) or dual feasibility (in dual simplex)
